apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: license
  labels:
    service: license
...
spec:
  podSelector:
    matchLabels:
      service: license
...
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            service: proxy
...
      ports:
        - protocol: TCP
          port: 8080
