apiVersion: v1
kind: Service
metadata:
  name: proxy
...
  labels:
    service: proxy
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
...
spec:
  type: {{ default "LoadBalancer" .Values.service.type }}
  ports:
    - port: {{ default 443 .Values.service.httpsPort }}
      targetPort: 8443
      protocol: TCP
      name: https
